// 定义行为

// actions.js
export const UPDATE_ASSUMPTIONS = 'UPDATE_ASSUMPTIONS';
export const UPDATE_RULES = 'UPDATE_RULES';
export const UPDATE_LOCALS = 'UPDATE_LOCALS';
export const UPDATE_AXIOM = 'UPDATE_AXIOM';
export const UPDATE_LOCAL_VARS = 'UPDATE_LOCAL_VARS';
export const UPDATE_SELECTED_SUB_TERM = 'UPDATE_SELECTED_SUB_TERM';
export const UPDATE_TEXT = 'UPDATE_TEXT';
export const INVOKE_SELECT_SUB_TERM = 'INVOKE_SELECT_SUB_TERM';
export const UPDATE_ASSIST_TERMS = 'UPDATE_ASSIST_TERMS';